/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalKendaraan;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author Mrz
 */
public class kendaraan extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;
    /**
     * Creates new form kendaraan
     */
    public kendaraan() {
        initComponents();
        tampilData();
    }
    
    public void dbConn(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/db_rentalkendaraan","root","");
            cn = conn.createStatement();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilData(){
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID Kendaraan");
        tabelnyo.addColumn("Status Tersedia");        
        tabelnyo.addColumn("Jenis Kendaraan");
        tabelnyo.addColumn("Merek Kendaraan");
        tabelnyo.addColumn("Model");
        tabelnyo.addColumn("Tahun");
        tabelnyo.addColumn("Nomor Polisi");
        tabelnyo.addColumn("Warna");
        tabelnyo.addColumn("Harga per hari");

        try{
            String idJenis = String.valueOf(penyewaan.jComboBox1.getSelectedItem());
            dbConn();
            String sql = "select tbl_kendaraan.id_kendaraan, tbl_kendaraan.status_tersedia, tbl_jenis.jenis, tbl_merek.merek, tbl_kendaraan.model, tbl_kendaraan.tahun_pembuatan, tbl_kendaraan.nomor_polisi, tbl_kendaraan.warna, tbl_kendaraan.harga_sewa_per_hari from tbl_kendaraan join tbl_jenis on tbl_jenis.id_jenis = tbl_kendaraan.id_jenis join tbl_merek on tbl_merek.id_merek = tbl_kendaraan.id_merek where tbl_jenis.jenis='" + idJenis + "' ORDER BY tbl_kendaraan.status_tersedia DESC";
            ResultSet rs = cn.executeQuery(sql);
            while(rs.next()){
                tabelnyo.addRow(new Object[]{
                rs.getString(1),
                "1".equals(rs.getString(2)) ? "TERSEDIA" : "TIDAK TERSEDIA",
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),    
                rs.getString(9),
                });
            }
            jTable1.setModel(tabelnyo);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Kesalahan" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Cari Model Kendaraan");

        jTextField1.setToolTipText("Cari berdasarkan Nomor Polisi / Merek / Model");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row;
        row=jTable1.getSelectedRow();
        
        penyewaan.txtIdKendaraan.setText(jTable1.getValueAt(row, 0).toString());
        penyewaan.txtMerek.setText(jTable1.getValueAt(row, 3).toString());
        penyewaan.txtModel.setText(jTable1.getValueAt(row, 4).toString());
        penyewaan.txtTahun.setText(jTable1.getValueAt(row, 5).toString());
        penyewaan.txtNopol.setText(jTable1.getValueAt(row, 6).toString());
        penyewaan.txtWarna.setText(jTable1.getValueAt(row, 7).toString());
        penyewaan.txtHarga.setText(jTable1.getValueAt(row, 8).toString());
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID Kendaraan");
        tabelnyo.addColumn("Status Tersedia");        
        tabelnyo.addColumn("Jenis Kendaraan");
        tabelnyo.addColumn("Merek Kendaraan");
        tabelnyo.addColumn("Model");
        tabelnyo.addColumn("Tahun");
        tabelnyo.addColumn("Nomor Polisi");
        tabelnyo.addColumn("Warna");
        tabelnyo.addColumn("Harga per hari");

        try{
            String idJenis = String.valueOf(penyewaan.jComboBox1.getSelectedItem());
            dbConn();
            String sql = "SELECT tbl_kendaraan.id_kendaraan, tbl_kendaraan.status_tersedia, tbl_jenis.jenis, tbl_merek.merek, tbl_kendaraan.model, tbl_kendaraan.tahun_pembuatan, tbl_kendaraan.nomor_polisi, tbl_kendaraan.warna, tbl_kendaraan.harga_sewa_per_hari " +
             "FROM tbl_kendaraan " +
             "JOIN tbl_jenis ON tbl_jenis.id_jenis = tbl_kendaraan.id_jenis " +
             "JOIN tbl_merek ON tbl_merek.id_merek = tbl_kendaraan.id_merek " +
             "WHERE tbl_jenis.jenis='" + idJenis + "' AND tbl_kendaraan.model LIKE '%" + jTextField1.getText() + "%'"
                    + "ORDER BY tbl_kendaraan.status_tersedia DESC";

            ResultSet rs = cn.executeQuery(sql);
            while(rs.next()){
                tabelnyo.addRow(new Object[]{
                rs.getString(1),
                "1".equals(rs.getString(2)) ? "TERSEDIA" : "TIDAK TERSEDIA",
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),    
                rs.getString(9),
                });
            }
            jTable1.setModel(tabelnyo);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Kesalahan" + e.getMessage());
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
